---
version: '3'
services:
  website:
    image: yadm/jekyll:2019-10-17
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - jekyll-bundle:/usr/local/bundle
    command: jekyll serve --config _config.yml,_dev.yml -t --watch --incremental
volumes:
  jekyll-bundle:
